---
- name: Spring-Petclinic Deployment In Linuxserver
  hosts: all
  become: yes
  vars: 
    java_packages: openjdk-11-jdk
    app_dir: /usr/share/springpetclinic
    app_download_url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
    app_file_name: spring-petclinic-2.4.2.jar
    app_username: springbootuser 
  tasks:  
    - name: update ubuntu packages and install java
      apt: 
        name: "{{java_packages}}"
        update_cache: yes
        state: present
    - name: create Spring Petclinic directory
      file: 
        path: "{{app_dir}}"
        state: directory
    - name: download SpringPetclinic 
      get_url: 
        url: "{{app_download_url}}"
        dest: "{{app_dir}}/{{app_file_name}}"
    - name: adduser SpringPetclinic
      user: 
        name: "{{app_username}}"
        password: "{{app_username}}"
        state: present
    - name: change ownership of jar file
      file: 
        path: "{{app_dir}}/{{app_file_name}}" 
        owner: "{{app_username}}" 
        mode: '500'
        state: file
    - name: Copy a "sudoers" f ile on the remote machine for editing
      ansible.builtin.copy:
        src: /etc/sudoers
        dest: /etc/sudoers.edit
        remote_src: yes
