---
- name: Spring-Petclinic Deployment In Linuxserver
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu packages and install java
      apt: 
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: create Spring Petclinic directory
      file: 
        path: /usr/share/springpetclinic
        state: directory
    - name: download SpringPetclinic 
      get_url: 
        url:  https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        dest: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
    - name: adduser SpringPetclinic
      user: 
        name: springbootuser
        password: springbootuser
        state: present
    - name: change ownership of jar file
      file: 
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar
        owner: springbootuser
        mode: '500'
        state: file
    - name: copy the jar file
      copy: 
        dest: /etc/systemd/system/springpetclinic.service
        src: SpringPetclinic.service
    - name: enable and start Spring-Petclinic
      systemd: 
        name: SpringPetclinic.service
        state: started
